### ISSUE TITLE
Method to preserve carriage returns in text input

### ISSUE THREAD

**Issue by rgvy** [delight-im/PHP-Foundation-Core#2]
Hello

Just a quick one. Filtering input with `DATA_TYPE_STRING` removes carriage return and linefeeds (newlines). Sometimes it is useful capture these from a `<textarea>`.

They get stripped because `FILTER_FLAG_STRIP_LOW` is always used by default on `filter_input`.

Perhaps there could be a  new type `DATA_TYPE_RAWTEXT` or something which excludes the flag?

**Comment by ocram** [comment]
Thanks, good point!

So you would agree that adding another mode (`DATA_TYPE_*`) would be better than changing the behavior of the existing one (`DATA_TYPE_STRING`), right? What about `DATA_TYPE_MULTILINE_STRING` or `DATA_TYPE_LONGTEXT`?

We'll have to see what's the best way to prevent the newlines from being removed while keeping the other parts of the behavior.

**Comment by rgvy** [comment]
Yes, I agree it's good to separate basic strings from multiline strings. It's probably safer and multiline strings are an edge case.

**Comment by rgvy** [comment]
As far as details:
`DATA_TYPE_LONGTEXT` looks good.

The easiest way to implement this might be just a simple switch like:
```php
$flags = $type == self::DATA_TYPE_LONGTEXT ? self::FLAGS_LONGTEXT : self::FLAGS
$filtered = filter_input(INPUT_GET, $key, $type, $flags);
```

**Comment by ocram** [comment]
Thanks!

We'll use the existing `DATA_TYPE_STRING` and the new `DATA_TYPE_LONGTEXT` (or `DATA_TYPE_LONG_TEXT` or just `DATA_TYPE_TEXT`?) then.

Regarding the implementation, the thing is that using `FILTER_FLAG_STRIP_LOW` is really convenient, but unfortunately, there's no similar flag that we could use for the new behavior, it seems. So if we want that new behavior, we probably have to drop that flag altogether (at least for the new mode) and implement a custom solution for stripping those bytes.

The flag `FILTER_FLAG_STRIP_LOW` removes the ASCII characters 0 to 31, which we really want (mostly). ASCII characters 10 and 13 are really the exception. But since there is no `FILTER_FLAG_STRIP_LOW_BUT_KEEP_NEWLINES`, we'll have to use a regular expression or something like that. Right?

**Comment by rgvy** [comment]
Hmmm maybe this is more complicated than I originally thought... Maybe it's ok to retain all characters below 31 if it's positioned as `DATA_TYPE_RAWTEXT`? Additionally, I was thinking it could be a good idea to retain the tab character...

This raw feature might be more useful than just for web applications. Some non-JSON REST API might benefit from including ascii control characters...

**Comment by ocram** [comment]
You're right, the tab character is something that we'd want to keep as well.

We could use

```php
if ($type === self::DATA_TYPE_LONGTEXT) {
    $flags = self::FLAGS & ~FILTER_FLAG_STRIP_LOW;
}
else {
    $flags = self::FLAGS;
}
```

to disable the `FILTER_FLAG_STRIP_LOW` filter for the new mode and then

```php
$filtered = preg_replace('/[\x00-\x08\x0b-\x0c\x0e-\x1f]/', '', $filtered);
```

to achieve the same effect again, but keeping CR, LF and tab. That should work.

I think you really don't want those [non-printable characters](https://en.wikipedia.org/wiki/ASCII#Control_characters) in most (or even all) cases.

**Comment by rgvy** [comment]
One implementation possibility would be to offer a single method in the `Input` class to handle long text. It could take GET/POST/COOKIE as a parameter. Something like:
`$app->input()->longtext(INPUT_POST, 'txtAccountProfile');`

This could avoid bloating the other methods...

**Comment by ocram** [comment]
After some major refactoring in https://github.com/delight-im/PHP-Foundation-Core/commit/364562c07df1f862ac1017852ba49e03fb0c9051, the implementation of `DATA_TYPE_TEXT` (went with the shorter name) became quite simple in https://github.com/delight-im/PHP-Foundation-Core/commit/d783885f4317183a10b46491ba4dfcf3769bca3c, with the additional introduction of `DATA_TYPE_RAW` in https://github.com/delight-im/PHP-Foundation-Core/commit/4a7f633b4ecb6eff27467821ad43c14cfdd9e9d8.

After upgrading the core via

```
$ composer update delight-im/foundation-core
```

you should be able to use the two new constants

```
\Delight\Foundation\Input::DATA_TYPE_TEXT
// or
\Delight\Foundation\Input::DATA_TYPE_RAW
```

instead of

```
TYPE_STRING
// or
\Delight\Foundation\Input::DATA_TYPE_STRING
```

now. The two shorthands `TYPE_TEXT` and `TYPE_RAW` are not available yet but will be added if things work correctly.

So these two new flags should do exactly what was missing. Would love to hear if those work as intended!

**Comment by rgvy** [comment]
Wow, another elegant implementation! :)

I can confirm the functionality is successful and was able to use `TYPE_TEXT` and `TYPE_RAW` by adding them with the other globals

**Comment by ocram** [comment]
Thank you so much!

Added the global shorthands as well now: https://github.com/delight-im/PHP-Foundation/commit/feb73d34ecde930bc44c8dc5d5172e1c86ab496e
