### ISSUE TITLE
Suggested Enhancements to App.php

### ISSUE THREAD

**Issue by rgvy** [delight-im/PHP-Foundation-Core#3]
Hello

Once again, I'll mention my gratitude for using this extremely simple, powerful, and elegant framework! Out of the box, it has nearly every feature and shortcut that fits with my style of coding. However, I did make a few modifications, which I'll detail below. Perhaps they can be incorporated, or else just provide advise for other users.

1) The only code in the framework that I actually modify is removing `final` to make the App class inheritable. This is to accomplish the rest of these modifications.
2) Addition of a method to force https:
```php
function forceSecure()
{
	if (!$this->isSecure())
	{
		header('Location: https://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']);
		exit();
	}
}
```
3) Checking to see if upload is present. This is to avoid having to load and start the `FileUpload` code and handling exceptions for optional uploads.
```php
function hasUpload($name)
{
	return isset($_FILES[$name]) && $_FILES[$name]['error'] != UPLOAD_ERR_NO_FILE;
}
```
4) Enhancement to `getClientIp()` from http://roshanbh.com.np/2007/12/getting-real-ip-address-in-php.html
```php
function getClientIp()
{
	if (!empty($_SERVER['HTTP_CLIENT_IP']))
		$ip = $_SERVER['HTTP_CLIENT_IP'];
	else if (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))
		$ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
	else
		$ip = $_SERVER['REMOTE_ADDR'];
	return $ip;
}
```
5) I would love to see `TemplateManager` (and maybe others, but especially `TemplateManager`) created lazily. TWIG loads many many classes by default before rendering a single template. Templates are unnecessary for use in a JSON REST API (although still possible). However, the magical php `json_encode` method combined with the great `Db` interface in this framework make it super simple to build such an API. Templates are just overhead in this case.

Thanks for considering my suggestion!

**Comment by ocram** [comment]
Thank you so much!

It's great to hear your appreciation again, and we should definitely incorporate some of your proposed changes. Let's see …

 1. Extending the `App` class is only useful if you change [how the application instance is created](https://github.com/delight-im/PHP-Foundation/blob/d99d99a46c77eb606f9a071370a5ee036a9b9328/index.php#L77), isn't it? Did you change that as well?
 2. I'm not sure if that's really the best way to do that. The `.htaccess` file that is included with this framework should include a section for redirecting all HTTP traffic to HTTPS. You just have to uncomment some lines. Can you try that? (Or did you try that already and there was a problem with that solution?)
 3. I could imagine two functions like this, including the one you suggested:

    ```php
    function hasUploads() {
        return !empty($_FILES);
    }

    function hasUpload($name) {
        return isset($_FILES[$name]) && $_FILES[$name]['error'] != UPLOAD_ERR_NO_FILE;
    }
    ```

    But it's important to note that loading the `FileUpload` component has a pretty negligible overhead only. In the end, this may just add complexity both to this framework and to your application. So I really wouldn't do this for performance reasons. But if it simplifies the logic of your application, e.g. because your form has an *optional* file upload, this might be a good idea.

    Anyway, we'd have to modify the second function so that it processes arrays like `my-input[]` correctly as well.

 4. I don't think that's a good idea. The first two values are parsed from HTTP request headers, so they can be spoofed as your "attacker" likes. Since these two values even *override* the value from `$_SERVER['REMOTE_ADDR']`, you just have to make your browser or client send one of the two headers as `1` or any other "truthy" value and your real IP address will not be recorded as a result.

 5. Absolutely! Couldn't agree more. Where possible, all components should be created lazily, as is done in several places already. Let's check what we can improve:

    * The member `$router` must be created immediately because it is always required. It is used to parse the request and to decide what code to execute. No way around that, right?
    * The member `$db` is not loaded lazily because it is required to create the `$auth` member. If we could make the latter load lazily, we could also defer the former. Please note, however, that the `$db` member itself does *not* establish a database connection. That, in turn, is already done lazily.
    * The member `$inputHelper` could indeed be deferred so that it loads lazily, as far as I can see.
    * The member `$templateManager` is loaded immediately because we want to inject the `App` instance as a global for all templates/views. As far as I can see, that's the only reason why it's not deferred. But injecting that global could also be done lazily, right? If I haven't missed anything so far, we could indeed make Twig load lazily, which you requested. That would be the greatest benefit among all those components, for sure.
    * The member `$mail` is already loaded lazily.
    * The member `$auth` is instantiated immediately because it creates the session. Loading that component was done lazily before, but if you start a session in your application or read/write the `$_SESSION` globals, this won't work. So it was changed to load immediately again, which I don't see any way around, unfortunately.
    * The member `$ids` is already loaded lazily.
    * The member `$flash`, again, is something whose construction could be deferred. I don't see why it's not done yet.

**Comment by rgvy** [comment]
Thanks for considering my ideas and the thoughtful feedback!

1) Yes, I've modified the `index.php` bootstrapper to use my extended `App` class. I've also added support for things like logging and some other useful globals (ex. a `slugify` function)
2) Great point! Originally I thought only to secure pages after the user is logged in. This would allow ISP caching of my static pages and resources. However, I now realize that every page does have at least a little dynamic content (even if it's just a logged-in indicator for the user)... I'm not too good with `.htaccess`, if I require https as you mention, does that exclude the `/public/` directory? It would be nice if those file were able to be cached by ISPs.
3) It's true that loading `FileUpload` isn't too heavy. I should have emphasized that my main purpose was more linear logic. Specifically, I prefer to avoid the entire try/catch block if the upload is not present. I will investigate uploaded file arrays with php and propose another method implementation.
4) Excellent point. I forgot to consider security for this one. At some point I can imagine my app sitting behind a load balancer, so I will defer the issue until later...
5) Awesome! I noticed that `$app->view` accesses the `$templateManager` directly instead of with  `getTemplateManager()`. As for the others, `$router, $db, $auth` all are tightly coupled so it doesn't make sense for them to be lazy. It seems like `$flash, $inputHelper` are very lightweight but could very easily be made lazy.  `$mail, $templateManager` definitely seem like the most heavy ones and the most optional for users of the framework.

**Comment by ocram** [comment]
Thanks!

 1. That makes sense. Wanted to verify that this is how you're doing this. The `App` class is now open for extension: https://github.com/delight-im/PHP-Foundation-Core/commit/b9a5f9eef0d8a633690f60ccbd4c17b81e424c06

 2. This does include all paths by default, i.e. also the `public` directory. Is ISP caching really that important? Normally, it's a best practice to send *everything* over HTTPS, not just dynamic content, but also static assets, such as CSS, JavaScript and images. For JavaScript, you will even get warnings on an HTTPS site if JavaScript is delivered via plain HTTP. Modern browsers show "mixed content" warnings. For the HTML pages themselves, the case is even more clear. As per current recommendations, you should send *every* page over HTTPS, not just the login page or those pages for authenticated users. In the future, modern browsers will probably warn on every non-HTTPS page. The direction is obvious. By the way, the lines that have to be uncommented in the included `.htaccess` are marked as such. If really necessary, files in the `public` folder could probably be excluded, but that requires some more skills with regard to the `.htaccess`.

 3. Great, the more linear logic is exactly what I thought about. Good point! Let's track this here: https://github.com/delight-im/PHP-Foundation-Core/issues/4

 4. Okay, let's ignore this for now. That solution has to be determined on a case-by-case basis. If you know that you can trust your load balancer with *some* headers, you can implement an individual solution that works in that setup. But I don't think there's a general solution to this problem.

 5. Sounds good! I think we can make the `TemplateManager` member lazy as well with some refactoring. We can track the helpers whose construction could be deferred here: https://github.com/delight-im/PHP-Foundation-Core/issues/5 and https://github.com/delight-im/PHP-Foundation-Core/issues/6 and https://github.com/delight-im/PHP-Foundation-Core/issues/7 Since `$mail` and `$ids` are already deferred while `$router`, `$db`, `$auth` are probably coupled too tighly, as you said, that's all we can do, I think. But, after all, that's three more members which can be deferred, including the heavy `TemplateManager`. Not bad.

**Comment by rgvy** [comment]
Cool. I'll get to work and submit some Pull Requests soon!

Regarding Item 2, thanks for your advice! I'll modify that `.htaccess` file as you describe.

**Comment by ocram** [comment]
As far as I can see, all points have either been resolved or been handled in separate issues now. So I'm going to close here.

Thanks again for this very valuable input!

**Comment by rgvy** [comment]
Wow, you're fast! I was going contribute, but you beat me to it :)

Thx for using these ideas!

**Comment by ocram** [comment]
No problem! Your ideas were more important than the (relatively quick) implementation – thanks!
